### ISSUE TITLE
New sample is there?

### ISSUE THREAD

**Issue by tshirai1027** [docusign/sample-app-loanco-nodejs#1]
Hi,
I saw the latest code of LoanCo application and found out some new codes are included. It could be some kinds of new sample (probably Land Purchase with purchase-land.js?). Can this be worked now too? or still under the development?
Your kind support is much appreciated.

**Comment by LarryKlugerDS** [comment]
Updated: purchase-land is included in the code, but is not one of the examples. It should not be used at this time.

**Comment by tshirai1027** [comment]
Thanks, then when I go to the website, I can input items there. However when I push the button “Begin Signing”, i’m getting the following errors;

PAGE ERROR
TypeError: envDef.setEmailSubject is not a function at /home/docusign/loanco.e518feeb0c/routes/purchase-land.js:25:9 at Layer.handle [as handle_request] (/home/docusign/loanco.e518feeb0c/node_modules/express/lib/router/layer.js:95:5) at next (/home/docusign/loanco.e518feeb0c/node_modules/express/lib/router/route.js:137:13) at Route.dispatch (/home/docusign/loanco.e518feeb0c/node_modules/express/lib/router/route.js:112:3) at Layer.handle [as handle_request] (/home/docusign/loanco.e518feeb0c/node_modules/express/lib/router/layer.js:95:5) at /home/docusign/loanco.e518feeb0c/node_modules/express/lib/router/index.js:281:22 at Function.process_params (/home/docusign/loanco.e518feeb0c/node_modules/express/lib/router/index.js:335:12) at next (/home/docusign/loanco.e518feeb0c/node_modules/express/lib/router/index.js:275:10) at Function.handle (/home/docusign/loanco.e518feeb0c/node_modules/express/lib/router/index.js:174:3) at router (/home/docusign/loanco.e518feeb0c/node_modules/express/lib/router/index.js:47:12)


It looks the function setEmailSubject is still not in the latest docusign-esign...does the latest one have the function?

**Comment by LarryKlugerDS** [comment]
Thank you for the bug report. I have filed internal ticket DEVDOCS-1650

**Comment by LarryKlugerDS** [comment]
I'm closing this issue since it is handled via the Jira and @tshirai1027 is a DS employee
