### ISSUE TITLE
doc.setDocumentBase64 is not a function 

### ISSUE THREAD

**Issue by AnanthiGopal** [docusign/sample-app-loanco-nodejs#2]
Getting the error 'doc.setDocumentBase64 is not a function '              
                    var envDef = new docusign.EnvelopeDefinition();
                    var filePath='pdfs/ESO.docx';
                    var fileBytes = null;
                    try {
                        // read file from a local directory
                        fileBytes = fs.readFileSync(path.resolve(__dirname+'/'+filePath));
                    } catch (ex) {
                        // handle error
                        console.log('Exception: ' + ex);
                    }

                    // add a document to the envelope
                    var doc = new docusign.Document();
                    
                     var base64Doc = new Buffer(fileBytes).toString('base64');
                     doc.setDocumentBase64(base64Doc);

**Comment by Ergin008** [comment]
+Nick

Nick can you look into this Loanco issue?  Hoping it’s an issue specific to this developer and not a broader issue.

**Comment by nicholasareed** [comment]
@AnanthiGopal did you make any modifications before running the sample? Perhaps you are using version 3 of the SDK (loanco support v2)?
