### ISSUE TITLE
Solution wont start

### ISSUE THREAD

**Issue by ECDonelson** [docusign/sample-app-loanco-nodejs#3]
Here's the stack

Not including .env
HTTPS server failed to start. Missing key or crt
{ Error: getaddrinfo ENOTFOUND undefined.docusign.net undefined.docusign.net:443
    at errnoException (dns.js:55:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'undefined.docusign.net',
  host: 'undefined.docusign.net',
  port: 443,
  response: undefined }
loginToDocuSign failure
{ Error: getaddrinfo ENOTFOUND undefined.docusign.net undefined.docusign.net:443
    at errnoException (dns.js:55:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'undefined.docusign.net',
  host: 'undefined.docusign.net',
  port: 443,
  response: undefined }

I have defined the .env file, and filled it in with the appropriate information, but its not finding it, what am I missing?

**Comment by mmallis87** [comment]
@ECDonelson make sure the .env file is on the root of the folder. So after you clone this repo,
```
cd sample-app-loanco-nodejs
vim .env
```
and then fill the info like mentionned in the configuration section of the README: https://github.com/docusign/sample-app-loanco-nodejs#configuration

**Comment by ECDonelson** [comment]
Thanks for the reply, I finally figured it out yesterday, but I'm having an issue with it creating the template. This is the error I get: 

{ errorCode: 'RECIPIENTS_NOT_PROVIDED',
  message: 'No recipients were found in the request.' }

The fix for yesterday was not adding a "something.env" file, it was just adding a ".env" file, which was not clear in the instructions, but I digress.

I fill out the information on the page, hit the submit button, and the above error comes up. I've added the right integrator key, and the proper template id, but still no luck. Any suggestions?

**Comment by mmallis87** [comment]
.env (dotenv) is a famous system in the Node.js world and we use it in this sample app. It's obviously not required to use it with the DocuSign SDK.

WRT the error, it seems to me that you forgot to add recipients (usually signers) to your template. The documentation explains how to define templates: https://developers.docusign.com/esign-rest-api/guides/features/templates
