### ISSUE TITLE
Bootstrap's JS doesn't load properly

### ISSUE THREAD

**Issue by RedRiderX** [docusign/sample-app-loanco-nodejs#5]
When bringing up an example in chrome I get this error

```
Uncaught Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3
```

Seems to be caused by the recent update to jQuery in https://github.com/docusign/sample-app-loanco-nodejs/commit/9a5eb1cb3fd07b1a1833ea63d34074675ea284d2#diff-e5530d98691a3fe2c144f9f309e7e2cc6fcc4891bb50b094caf5393380a1d75eR22

Easiest fix should be to bump Bootstrap up to 3.3.7: https://github.com/twbs/bootstrap/issues/16834#issuecomment-251996660

**Comment by ivdinkovds** [comment]
@RedRiderX Thank you for notifying us for this  issue. FYI case number DEVDOCS-4068

**Comment by InbarGazit** [comment]
@RedRiderX  we will fix this, but just wanted to also mention that PRs are welcome in this repo....

**Comment by ivdinkovds** [comment]
Fix deployed. Closing the issue
