### ISSUE TITLE
Requiring to create/login docusign account

### ISSUE THREAD

**Issue by rad182** [docusign/sample-app-loanco-nodejs#7]
Would like to know why when I try to run this sample code it requires me to login to docusign when clicking loan buttons, while when testing https://loanco.sampleapps.docusign.com doesn't require me to login to docusign.

am I missing something?
TIA

**Comment by InbarGazit** [comment]
The code in GitHub uses Auth Code Grant, which requires user to log in, the code we deployed to the site is using JWT which doesn't, and we hardcoded our own account.
